source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.0"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.2.1"

# User PostgreSQL
gem "pg"

# Use Puma as the app server
gem "puma", "~> 3.11"

gem "baby_squeel", github: "rzane/baby_squeel"
gem "enumerize", github: "brainspec/enumerize"
gem "meta-tags"

gem "rollbar"

# bulk insert
gem "activerecord-import"

# whenever
gem "whenever", require: false

# Reduces boot times through caching; required in config/boot.rb
# gem 'bootsnap', require: false

gem "capybara"
gem "selenium-webdriver"
gem "chromedriver-helper"
gem "capybara-sessionkeeper"

gem "active_type"

gem "dotenv-rails"

gem "simple_scheduler"

gem "fast_jsonapi"
gem "rails_pretty_json_rednerer"
gem "rack-cors", require: "rack/cors"

gem "ridgepole"
gem "seed-fu"

gem "sidekiq"
gem "rails_db"
gem "logster"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "pry"
  gem "pry-byebug"
  gem "pry-rails"
  gem "awesome_rails_console"
  gem "rails-controller-testing"
  gem "spring-commands-rspec"
  gem "rspec-rails"
  gem "rspec_junit_formatter", "0.2.2" # for circleci
  gem "touch_action"

  gem "rubocop"
  gem "rubocop-rails_config"

  gem "factory_bot_rails"

  gem "rails-i18n"
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"

  gem "better_errors"
  gem "annotate"
  gem "view_source_map"
  gem "solargraph"
end
