default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: root
  password:

development:
  <<: *default
  database: auto-matching_development

test:
  <<: *default
  database: auto-matching_test

production:
  <<: *default
  database: auto-matching_production
  url: <%= ENV['DATABASE_URL'] %>
